name: "Update GitLab hashes dictionary"
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Process missing tags
        working-directory: ./automation
        run: |
          # curl -s https://registry.hub.docker.com/v2/repositories/gitlab/gitlab-ce/tags -o gitlab-ce_tags.json
          # curl -s https://registry.hub.docker.com/v2/repositories/gitlab/gitlab-ee/tags -o gitlab-ee_tags.json
          python get_gitlab_hashes.py ../gitlab_hashes.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automatic update
